user_index:
    path:     /
    defaults: { _controller: "DLGlobalBundle:CoreUserUser:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "DLGlobalBundle:CoreUserUser:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "DLGlobalBundle:CoreUserUser:new" }
    methods:  [GET, POST]


user_edit:
    path:     /{id}/edit
    defaults: { _controller: "DLGlobalBundle:CoreUserUser:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "DLGlobalBundle:CoreUserUser:delete" }
    methods:  DELETE
