tree_service:
    path:     /f/{neud_id}
    defaults: { _controller: "DLGlobalBundle:Tree:getTreeById" }
    methods:  GET
mytree_view:
    path:     /arbo/{neud_id}
    defaults: { _controller: "DLGlobalBundle:Tree:Treemy" }
    methods:  GET
earn_view:
    path:     /earn/{neud_id}
    defaults: { _controller: "DLGlobalBundle:Tree:getearn" }
    methods:  GET
